### ISSUE TITLE
hardware wallet (ledger) support for updated terra station desktop app

### ISSUE THREAD

**Issue by theWorkMachine** [stationmoney/station#21]
I understand that a hardware ledger is no longer supported in the new updated version of terra station desktop app while it is still supported on the the chrome web extension. 

I just want to know if it is safe to downgrade my terra station app to the previous version where it was still supported. Is that a safe solution if I want to continue using hardware wallet on my desktop terra station app?

**Comment by simcheolhwan** [comment]
There is no previous version which supports ledger device.
Use chrome browser to connect with Ledger device please.

**Comment by orientalperil** [comment]
@theWorkMachine You cannot downgrade the desktop app because it loads the code from the internet.  So there is now no way to connect the desktop app with ledger.  The ledger support was removed from the desktop app but the developers literally did this for no reason and didn't tell anyone anywhere.  For more info see this conversation https://github.com/terra-money/station/issues/14

**Comment by simcheolhwan** [comment]
In fact, I answered the reason but you ignored my answer and defined your own conclusion in the link you shared :)

As I mentioned there, I suggest to stop this endless chase now. It doesn't make any productive result with just plenty of negative comments everywhere like this.

**Comment by orientalperil** [comment]
I didn't ignore your answer.  Your answer is illogical.

**Comment by simcheolhwan** [comment]
@orientalperil It is obvious that I am illogical. So could you stop to comment? You and I keep just endless conversation in multiple places. I hope you will kindly understand my request. Thank you :)
