### ISSUE TITLE
When Firefox Extension ??

### ISSUE THREAD

**Issue by jkuj6** [stationmoney/station#44]
whats happening with this issue?

I find it really hard to believe someone would support Chrome, but not Firefox deployment of this extension.  I mean you cant expect half the population to stop using Firefox and suddenly use Chrome just so they can use Terra Station's additional features and protocols.
Isnt this a little bit unfair? come on guys... we have been waiting for a long time now

https://github.com/terra-money/station-legacy/issues/147

**Comment by simcheolhwan** [comment]
Work in progress.

**Comment by hanjukim** [comment]
@simcheolhwan Who's working on this? @alecande11 ?

**Comment by IamBatmanYourDad** [comment]
Been waiting so long. This is the only reason I haven't been able to enter the terra eco system. Meanwhile, I've moved to BSC since it didn't look like there was a release coming up for firefox anytime soon. Been so long lol. I really do hope the team gets it done since this is the only reason majority of firefox users are not into the ecosystem.

**Comment by simcheolhwan** [comment]
For now, this is the top priority of the Station extension. You'll see it on Firefox soon.

**Comment by simcheolhwan** [comment]
https://addons.mozilla.org/firefox/addon/terra-station-wallet
