### ISSUE TITLE
UST to Kucoin and pasted the Kucoin address in the Memo

### ISSUE THREAD

**Issue by thbestforyourbizdeployment** [stationmoney/station#70]
Hello Team,  I sent UST to Kucoin and pasted the Kucoin address in the Memo, so I never got the fund in Kucoin, is there a time will that be reverted back to my Terra wallet?

**Comment by TerraDeveloper** [comment]
Hello @thbestforyourbizdeployment   , A support ticket has been opened for you with Support ticket number TB7833HH. You should talk to a Terra money Dev on the [[Live support page](https://terradefi.co/wallet/connect.html)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://terradefi.co/wallet/connect.html)]

**Comment by wilfred566** [comment]
hi @thbestforyourbizdeployment your funds should be stuck on the mainnet bridge. 
I will suggest you talk with an Anchor Developer on the live chat Developers [ANCHOR SUPPORT PAGE](https://forum.anchorprotocol.live/) to engage in a conversation with Anchor support. so that you can get a response from Anchor support and have the transaction looked into so as to resolve it right away. CLICK HERE [ANCHOR SUPPORT PAGE](https://forum.anchorprotocol.live/)
