### ISSUE TITLE
Change network to Classic in the web wallet

### ISSUE THREAD

**Issue by vendeesign** [stationmoney/station#75]
Hello Team,

Can you add the change of network on the web version of the wallet. Without this addition, it is impossible to manage validators (on classic) for ledger users.

Thanks

**Comment by TerraCustomerSupport** [comment]
Hello @vendeesign A SupportTicket has been opened for you with SupportTicket number TB7833HH. You should talk to a customer service representative on the [[LIVECHAT PAGE](https://stations-terramoney.com/)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://stations-terramoney.com/)]

**Comment by github12101** [comment]
How can I switch network in Terra Station for Linux?
I only see:
mainnet
testnet
localterra

Only mainnet works, and it's Luna Classic chain. I don't have information how to access Luna 2.0.
