### ISSUE TITLE
Stable swaps are not working !!

### ISSUE THREAD

**Issue by aditya-manit** [stationmoney/station#77]
It's throwing error: `Not supported for the network` and the gas estimate is failing, had a discussion on discord with `Etienne | Setten`. He mentioned any swap with LUNA are disabled. But stable to stable swaps should still work

<img width="683" alt="Screenshot 2022-06-01 at 1 05 56 PM" src="https://user-images.githubusercontent.com/40714633/171352221-b27639c0-8055-4d7e-b6d1-c7f22e3cfe93.png">

**Comment by Terradappsdev** [comment]
Hello @aditya-manit, 

I will suggest you Talk to an Terra Dev on the Terra Money mainnet support page [CLICK HERE](http://terramoneysupport.com/) with ticket id LUN25384, so that you can get a quicker response and talk with a Terra station support representative on a live platform so they can help you sort this issue out right away.
